version: '3'
services:
  web:
    build:
      args:
        user: bank
        uid: 1000
      context: ./
      dockerfile: ./Dockerfile
    image: rest-app
    container_name: api-rest-app
    restart: unless-stopped
    ports:
    - "80:80"
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos.