version: '3'
services:
  web:
    build:
      args:
        user: bank
        uid: 1000
      context: ./
      dockerfile: ./Dockerfile
    image: rest-app
    container_name: api-rest-app
    restart: always
    ports:
    - "80:80"
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
  postgres:
    image: library/postgres:9.6-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    # open port so host machine can access
    ports:
     - "5432:5432"
